version: 2
updates:
- package-ecosystem: npm
  directory: "/infra"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  ignore:
  - dependency-name: fastify
    versions:
    - ">= 3.a, < 4"
  - dependency-name: fastify-cookie
    versions:
    - ">= 4.a, < 5"
  - dependency-name: fastify-cookie
    versions:
    - ">= 5.a, < 6"
  - dependency-name: fastify-cors
    versions:
    - ">= 4.a, < 5"
  - dependency-name: fastify-cors
    versions:
    - ">= 5.a, < 6"
  - dependency-name: fastify-helmet
    versions:
    - ">= 4.a, < 5"
  - dependency-name: fastify-helmet
    versions:
    - ">= 5.a, < 6"
  - dependency-name: fastify-plugin
    versions:
    - ">= 2.a, < 3"
  - dependency-name: fastify-plugin
    versions:
    - ">= 3.a, < 4"
  - dependency-name: fastify-rate-limit
    versions:
    - ">= 4.a, < 5"
  - dependency-name: fastify-rate-limit
    versions:
    - ">= 5.a, < 6"
  - dependency-name: fastify-static
    versions:
    - ">= 3.a, < 4"
  - dependency-name: fastify-static
    versions:
    - ">= 4.a, < 5"
  - dependency-name: "@mando75/typeorm-graphql-loader"
    versions:
    - "> 0.3.0"
  - dependency-name: ts-jest
    versions:
    - "> 26.4.1, < 26.5"
  - dependency-name: typeorm
    versions:
    - "> 0.2.24, < 0.3"
  - dependency-name: fast-json-stringify
    versions:
    - 2.4.2
    - 2.6.0
  - dependency-name: "@algolia/client-search"
    versions:
    - 4.9.0
  - dependency-name: "@types/algoliasearch"
    versions:
    - 4.0.0
  - dependency-name: algoliasearch
    versions:
    - 4.9.0
  - dependency-name: date-fns
    versions:
    - 2.19.0
    - 2.20.1
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.2
    - 4.15.2
    - 4.16.1
    - 4.19.0
    - 4.21.0
  - dependency-name: "@types/ioredis"
    versions:
    - 4.22.3
  - dependency-name: ioredis
    versions:
    - 4.25.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.24
    - 14.14.35
    - 14.14.37
  - dependency-name: apollo-server-testing
    versions:
    - 2.19.2
    - 2.20.0
    - 2.21.0
    - 2.21.1
    - 2.21.2
    - 2.22.1
    - 2.22.2
  - dependency-name: apollo-server-fastify
    versions:
    - 2.19.2
    - 2.20.0
    - 2.21.0
    - 2.21.1
    - 2.21.2
    - 2.22.1
  - dependency-name: graphql-subscriptions
    versions:
    - 1.2.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.22
  - dependency-name: "@google-cloud/profiler"
    versions:
    - 4.1.1
  - dependency-name: ts-jest
    versions:
    - 26.5.2
  - dependency-name: jest-mock-extended
    versions:
    - 1.0.12
  - dependency-name: eslint
    versions:
    - 7.19.0
  - dependency-name: pino-pretty
    versions:
    - 4.5.0
