apiVersion: v1
kind: Secret
metadata:
  name: {{ template "daily-api.fullname" . }}
  labels:
    app: {{ template "daily-api.name" . }}
    chart: {{ template "daily-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  MYSQL_USER: {{ .Values.appConfig.mysql.user | b64enc }}
  MYSQL_PASSWORD: {{ .Values.appConfig.mysql.password | b64enc }}
  MYSQL_DATABASE: {{ .Values.appConfig.mysql.database | b64enc }}
  MYSQL_HOST: {{ .Values.appConfig.mysql.host | b64enc }}
  ADMIN_KEY: {{ .Values.appConfig.adminKey | b64enc }}
  TWITTER_CONSUMER_KEY: {{ .Values.appConfig.twitter.consumer.key | b64enc }}
  TWITTER_CONSUMER_SECRET: {{ .Values.appConfig.twitter.consumer.secret | b64enc }}
  TWITTER_ACCESS_TOKEN_KEY: {{ .Values.appConfig.twitter.accessToken.key | b64enc }}
  TWITTER_ACCESS_TOKEN_SECRET: {{ .Values.appConfig.twitter.accessToken.secret | b64enc }}
  SLACK_WEBHOOK: {{ .Values.appConfig.slackWebhook | b64enc }}
  ACCESS_SECRET: {{ .Values.appConfig.accessSecret | b64enc }}
  GATEWAY_SECRET: {{ .Values.appConfig.gatewaySecret | b64enc }}

