apiVersion: v1
kind: Secret
metadata:
  name: {{ template "daily-api.fullname" . }}
  labels:
    app: {{ template "daily-api.name" . }}
    chart: {{ template "daily-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  MYSQL_USER: {{ .Values.appConfig.mysql.user | b64enc }}
  MYSQL_PASSWORD: {{ .Values.appConfig.mysql.password | b64enc }}
  MYSQL_DATABASE: {{ .Values.appConfig.mysql.database | b64enc }}
  MYSQL_HOST: {{ .Values.appConfig.mysql.host | b64enc }}
  ADMIN_KEY: {{ .Values.appConfig.adminKey | b64enc }}
  COOKIES_DOMAIN: {{ .Values.appConfig.cookies.domain | b64enc }}
  COOKIES_KEY: {{ .Values.appConfig.cookies.key | b64enc }}
  TWITTER_CONSUMER_KEY: {{ .Values.appConfig.twitter.consumer.key | b64enc }}
  TWITTER_CONSUMER_SECRET: {{ .Values.appConfig.twitter.consumer.secret | b64enc }}
  TWITTER_ACCESS_TOKEN_KEY: {{ .Values.appConfig.twitter.accessToken.key | b64enc }}
  TWITTER_ACCESS_TOKEN_SECRET: {{ .Values.appConfig.twitter.accessToken.secret | b64enc }}
  GITHUB_CLIENT_ID: {{ .Values.appConfig.github.client.id | b64enc }}
  GITHUB_CLIENT_SECRET: {{ .Values.appConfig.github.client.secret | b64enc }}
  GOOGLE_CLIENT_ID: {{ .Values.appConfig.google.client.id | b64enc }}
  GOOGLE_CLIENT_SECRET: {{ .Values.appConfig.google.client.secret | b64enc }}
  JWT_SECRET: {{ .Values.appConfig.jwt.secret | b64enc }}
  JWT_AUDIENCE: {{ .Values.appConfig.jwt.audience | b64enc }}
  JWT_ISSUER: {{ .Values.appConfig.jwt.issuer | b64enc }}
  SLACK_WEBHOOK: {{ .Values.appConfig.slackWebhook | b64enc }}
  CODEFUND_API_KEY: {{ .Values.appConfig.codefundApiKey | b64enc }}

